name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: "windows-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup default stable

      - name: Run tests
        run: cargo test
